backend:
  name: github
  repo: zgunz42/adibite
  squash_merges: true
  open_authoring: true

#  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
#publish_mode: editorial_workflow

local_backend: true

site_url: https://adibite.xyz

publish_mode: editorial_workflow

media_folder: static/media
public_folder: /media

collections:
  - name: "blog"
    label: "Blog Post"
    folder: "content/posts/"
    format: "yaml-frontmatter"
    preview_path: "{{slug}}"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subTitle", widget: "string"}
      - {label: "Created Date", name: "createAt", widget: "datetime"}
      - {label: "Category", name: "category", widget: "text"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Image Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "page"
    label: "Blog Page"
    folder: "content/pages/"
    format: "yaml-frontmatter"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created Date", name: "createAt", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "meta"
    label: "Site Meta"
    files:
      - file: "content/meta/config.json"
        label: Config
        extension: "json"
        name: config
        fields:
          - {label: "Site Title", name: "siteTitle", widget: string}
          - {label: "Short Site Title", name: "shortSiteTitle", widget: string}
          - {label: "Site Description", name: "siteDescription", widget: string}
          - {label: "Site Url", name: "siteUrl", widget: string}
          - {label: "Path Prefix", name: "pathPrefix", widget: string, required: false}
          - {label: "Site Image", name: "siteImage", widget: string}
          - {label: "Site Language", name: "siteLanguage", widget: string}
          - {label: "Author Name", name: "authorName", widget: string}
          - {label: "Author TwitterAccount", name: "authorTwitterAccount", widget: string}
          - {label: "info Title", name: "infoTitle", widget: string}
          - {label: "info TitleNote", name: "infoTitleNote", widget: string}
          - {label: "Manifest Name", name: "manifestName", widget: string}
          - {label: "Manifest ShortName", name: "manifestShortName", widget: string}
          - {label: "Manifest StartUrl", name: "manifestStartUrl", widget: string}
          - {label: "Manifest BackgroundColor", name: "manifestBackgroundColor", widget: string}
          - {label: "Manifest ThemeColor", name: "manifestThemeColor", widget: string}
          - {label: "Manifest Display", name: "manifestDisplay", widget: string}
          - {label: "Contact Email", name: "contactEmail", widget: string}
          - {label: "Author SocialLinks", name: "authorSocialLinks", widget: list, fields: [{label: "Name", name: "name", widget: "string"}, {label: "url", name: "url", widget: "string"}]}
  - name: "part"
    label: "Site Part"
    files:
      - file: "content/parts/author.md"
        label: "Author"
        name: "author"
        format: "yaml-frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/parts/footnote.md"
        label: "Footnote"
        format: "yaml-frontmatter"
        name: "footnote"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/parts/info.md"
        label: "Info"
        format: "yaml-frontmatter"
        name: "info"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

